<a href="https://colab.research.google.com/github/Ujwala2003/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We first import numpy under the name np using the **import numpy as np** command.

In [3]:
import numpy as np

We create arrays in numpy using lists.

In [6]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


Converting a list into numpy array is done using np.array()

In [7]:
numpyarray=np.array(a)
print(numpyarray)

[1 2 3 4 5]


The version of numpy can be checked using  __version __.

In [9]:
print(np.__version__)

1.19.5


Shape of the array can be checked using the below command:

In [11]:
arr=np.array([8,2,5,6,9])
print(arr.shape)

(5,)


The datatype of the objects in array is found using arrayname.dtype

In [15]:
x=np.array([1.0,2.6,3.2,1.7])
print(x.dtype)

float64


A 3-dimensional array:

In [16]:
m = np.array([
    [[2,3,4],
        [3,5,6]],
    [[5,3,7,],
        [19,12,11]]
])
print(m.shape)
print(m.dtype)

(2, 2, 3)
int64


The dimensions of an array can be found using **arrayname.ndim**

In [17]:
print(m.ndim)
print(x.ndim)

3
1


Creating arrays with all zeroes using numpy.zeros().

In [19]:
a=np.zeros((2,2,1),dtype=np.int64)
print(a)

[[[0]
  [0]]

 [[0]
  [0]]]


Creating arrays with all zeroes using numpy.ones()

In [20]:
a=np.ones((2,2,1),dtype=np.int64)
print(a)

[[[1]
  [1]]

 [[1]
  [1]]]


We can reshape an array using reshape().We can give the new shape in brackets.

In [21]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr1=arr.reshape(2,2,3)
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Flattening the array can be done using flatten()

In [22]:
arr2=arr1.flatten()
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Data can be horizontally appended using hstack and vertically appended using vstack.

In [31]:
a = np.array([1,3,2,19])
b = np.array([2,11,7,9])
c = np.array([3,4,5,7])
print('Horizontally Appended--' , np.hstack((a,b,c)))

Horizontally Appended-- [ 1  3  2 19  2 11  7  9  3  4  5  7]


In [32]:
a = np.array([1,3,2,19])
b = np.array([2,11,7,9])
c = np.array([3,4,5,7])
print('Vertically Appended--' , np.vstack((a,b,c)))

Vertically Appended-- [[ 1  3  2 19]
 [ 2 11  7  9]
 [ 3  4  5  7]]


Random numbers can be generated using np.random.normal(loc, scale, size)

In [34]:
array=np.random.normal(8,0.2,15)
print(array)

[8.00360669 7.92904738 7.99034561 7.83393603 8.32991945 7.91682012
 8.36902851 8.06221627 7.94336373 7.91732416 8.02105751 8.04760498
 8.26803088 8.02647829 8.02781979]


To create an array with constantly spaced values, use np.arange(start, stop,step)[If step isn't give it takes default value 1]


In [36]:
np.arange(5,15,3)

array([ 5,  8, 11, 14])

In [37]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

Accesing rows and columns of an array by slicing:

In [39]:
a =np.array([(1,2,3), (4,5,6) , (7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
print('ROW 2-' , a[1])

ROW 2- [4 5 6]


In [44]:
print('COLUMN 3-' , a[:,2])

COLUMN 3- [3 6 9]


Finding maximum,minimum,mean,median,standard devation of an array:

In [47]:
x=np.array([2,3,32,21,33,12,33,11])
print(np.max(x))
print(np.min(x))
print(np.mean(x))
print(np.median(x))
print(np.std(x))


33
2
18.375
16.5
12.348456381264826


Dot product of 2 arrays can be found using np.dot().Input arrays must be 1-D or 2-D

In [48]:
a=np.array([2,8,5])
b=np.array([5,2,2])
np.dot(a,b)

36

Matrix Product of 2 arrays can be found using matmul() 
1) 2-D arrays, it returns normal product

2) Dimensions > 2, the product is treated as a stack of matrix

3) 1-D array is first promoted to a matrix, and then the product is calculated

In [49]:
mat1=[[4,5,6],[3,2,1],[1,3,7]]
mat2=[[10,2,3],[4,6,4],[8,3,4]]
np.matmul(mat1,mat2)

array([[108,  56,  56],
       [ 46,  21,  21],
       [ 78,  41,  43]])

Inverse of a matrix can be found using np.linalg.inv()

In [50]:
mat=[[4,5,6],[3,2,1],[1,3,7]]
print(np.linalg.inv(mat))

[[-0.78571429  1.21428571  0.5       ]
 [ 1.42857143 -1.57142857 -1.        ]
 [-0.5         0.5         0.5       ]]


Findind determinant of a matrix

In [51]:
mat=[[4,5,6],[3,2,1],[1,3,7]]
det = np.linalg.det(mat)
print(int(det))

-13


Finding the rank of matrix

In [52]:
mat=[[4,5,6],[3,2,1],[1,3,7]]
np.linalg.matrix_rank(mat)

3

Eigen values and eigen vectors of a matrix can be found using np.linalg.eig()

In [54]:
mat=[[2,4,5],[1,5,7],[9,4,2]]
eigenvalues, eigenvectors=np.linalg.eig(mat)
print(eigenvalues, eigenvectors)

[-4.01485615 -0.05716216 13.07201831] [[ 0.2637574  -0.23211519 -0.49898311]
 [ 0.57316926  0.80389169 -0.60222515]
 [-0.77582797 -0.54761363 -0.6231699 ]]


DIAGONAL of a matrix can be found using .diagonal()

TRACE of a matrix can be found using .trace()

TRANSPOSE of a matrix can be found using .transpose()

In [59]:
mat=np.array([[2,4,5],[1,5,7],[9,4,2]])
print('The matrix is\n',mat)
print('The diagonal of the matrix is',mat.diagonal())
print('The trace of the matrix is',mat.trace())
print('The tanspose of the matrix is\n',mat.transpose())

The matrix is
 [[2 4 5]
 [1 5 7]
 [9 4 2]]
The diagonal of the matrix is [2 5 2]
The trace of the matrix is 9
The tanspose of the matrix is
 [[2 1 9]
 [4 5 4]
 [5 7 2]]
